dayWeb/myshopping/goods/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(\d+)/add/$', views.add, name='add'),
    url(r'^index/$', views.index, name='index'),
    url(r'^findTypePid/$', views.findTypePid, name='findTypePid'),
    #显示所有商品
    url(r'^(\d+)/list/$', views.list, name='list'),
    #删除商品
    url(r'^(\d+)/(\d+)/delete/$', views.delete, name='delete'),
    #修改商品
    url(r'^(\d+)/update/$', views.update, name='update'),
    #购买时候商品详情
    url(r'^(\d+)/detail/$', views.detail, name='detail'),

]

dayWeb/myshopping/myshopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('users.urls', namespace='users')),
    url(r'^store/', include('store.urls', namespace='store')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^shopcart/', include('shopcart.urls', namespace='shopcart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
]

dayWeb/myshopping/orders/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    #确认订单
    url(r'^confirm/$', views.confirm, name='confirm'),
    #支付订单
    url(r'^pay/$', views.pay, name='pay'),
    #生成订单
    url(r'^done/$', views.done, name='done'),
    #查看订单
    url(r'^list/$', views.list, name='list'),
    #订单详情
    url(r'^(\d+)/detail/$', views.detail, name='detail'),
    #删除订单
    url(r'^(\d+)/delete/$', views.delete, name='delete'),

]

dayWeb/myshopping/shopcart/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [

    url(r'^(?P<count>\d+)/(?P<goods_id>\d+)/add/$', views.add, name='add'),#第一个数字为数量，第二个数字为商品id
    url(r'^list/$', views.list, name='list'),
    #删除购物车商品
    url(r'^(\d+)/delete/$', views.delete, name='delete'),

]

dayWeb/myshopping/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_register/$', views.user_register, name='user_register'),
    url(r'^index/', views.index, name='index'),

    url(r'^login_success/$', views.login_success, name='login_success'),
    url(r'^register_success/$', views.register_success, name='register_success'),
    #登录成功的主页
    url(r'^user_index/$', views.user_index, name='user_index'),
    #个人资料
    url(r'^user_info/$', views.user_info, name='user_info'),
    #个人资料修改
    url(r'^user_update/$', views.user_update, name='user_update'),
    #退出
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    # 添加收获地址
    url(r'^add_address/$', views.add_address, name='add_address'),
    #查看所有收获地址
    url(r'^list_address/$', views.list_address, name='list_address'),
    #删除收获地址
    url(r'^(\d+)/delete_address/$', views.delete_address, name='delete_address'),
    #修改收获地址
    url(r'^(\d+)/update_address/$', views.update_address, name='update_address'),
]

dayWeb/myshopping/goods/models.py
from django.db import models

# Create your models here.
# from myshopping.store.models import Store
from store.models import Store


class GoodsType(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, unique=True, verbose_name='商品类型名称')
    cover = models.ImageField(upload_to='static/imgs/goods', default='static/imgs/goods/aaa.png', verbose_name='商品类型插图')
    intro = models.TextField(verbose_name='商品类型描述')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, verbose_name='父级类型')


class Goods(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, verbose_name='商品名称')
    # price = models.DecimalField(max_digits=8, decimal_places=2)
    price = models.FloatField(verbose_name='商品单价')
    stock = models.IntegerField(verbose_name='库存')
    count = models.IntegerField(default=0, verbose_name='销量')
    createTime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    intro = models.TextField()
    store = models.ForeignKey(Store, on_delete=models.CASCADE, verbose_name='商品所属商店')
    goodstype = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name='商品类型')


class GoodsImage(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/imgs/goods', default='static/imgs/goods/aaa.png', verbose_name='商品图片')
    status = models.BooleanField(default=False, verbose_name='是否默认显示该图片')
    intro = models.TextField(null=True, blank=True, verbose_name='商品描述')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='所属商品')

dayWeb/myshopping/shopcart/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from goods.models import Goods


class ShopCart(models.Model):
    id = models.AutoField(primary_key=True)
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='购物车商品')
    count = models.IntegerField(verbose_name='商品数量')
    addTime = models.DateTimeField(auto_now_add=True, verbose_name='商品添加时间')
    allTotal = models.FloatField(verbose_name='小计金额')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='所属用户')

dayWeb/myshopping/shopcart/views.py
from django.shortcuts import render, redirect, reverse

# Create your views here.

from django.views.decorators.http import require_GET
from django.contrib.auth.decorators import login_required
from goods.models import Goods
from . import models


@require_GET
@login_required
def add(req, count, goods_id):
    goods = Goods.objects.get(pk=goods_id)
    user = req.user

    try:
        shopCart = models.ShopCart.objects.get(user=user, goods=goods)
        shopCart.count += int(count)
        shopCart.allTotal = shopCart.count * goods.price
        shopCart.save()
    except:
        shopCart = models.ShopCart(goods=goods, user=user)
        shopCart.count = int(count)
        shopCart.allTotal = shopCart.count * goods.price
        shopCart.save()

    return redirect(reverse('shopcart:list'))


#购物车的列表
@login_required
def list(req):
    shopcarts = models.ShopCart.objects.filter(user=req.user).order_by('-addTime')

    return render(req, 'shopcart/list.html', {'shopcarts': shopcarts})


#购物车的删除
def delete(req, shopcart_id):
    shopCart = models.ShopCart.objects.get(pk=shopcart_id)
    shopCart.delete()
    return redirect(reverse('shopcart:list'))

dayWeb/myshopping/shopcart/templates/shopcart/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购物车</title>
    <link rel="stylesheet" type="text/css" href="/static/css/shop-car.css">
    <link rel="stylesheet" type="text/css" href="/static/css/common.css">
    <link rel="stylesheet" type="text/css" href="/static/css/index.css">
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script src="/static/js/the_Same.js"></script>
    <script src="/static/js/shop-car.js"></script>
</head>
<body>



<!--导航-->
<div id="nav-wrap">
    <div id="nav">
        <ul>
            <li><a href="{% url 'users:user_index' %}" class="nav-page">首页</a></li>
            <li><a href="#">品牌特卖</a></li>
            <li><a href="#">女装折扣</a></li>
            <li><a href="#">品牌男装</a></li>
            <li><a href="#" >积分抽奖</a></li>
            <li><a href="#" >特价商品</a><span></span></li>
            <li><a href="#" class="nav-balabala">巴拉巴拉专区</a></li>
            <li><a href="#">签到换礼</a></li>
        </ul>

    </div>
</div>
<!--购物车内容-->
<div class="shopping_car_wrap">
    <div class="shopping_car">
        <div class="shop_menu"><img src="/static/imgs/img/shopping_car.jpg"></div>
		<form action="{% url 'orders:confirm' %}" method="post">
			{% csrf_token %}
        <div class="updater-list">
            <table class="shop_table">
                <thead>
                    <tr>
                        <th colspan="2">商品</th>
       
                        <th width="100">商品数量</th>
                        <th width="100">商品单价</th>
                        <th width="100">商品总价</th>
                        <th width="80">操作</th>
                    </tr>
                </thead>
								{% for s in shopcarts %}
                <tbody>
                    <tr class="shop_car_con">
                        
                        <td width="300">
                            <p><input type="checkbox" name="s_id" value="{{s.id}}" />{{s.goods.name}}</p>
                            
                        </td>
												<td width="100"><a><img src="/{{s.goods.goodsimage_set.all.first.path}}"></a></td>
                        <td>
                            <div class=" clearfix">
                                
                                <input type="number" name="count" value="{{s.count}}" class="txt_3">
                                
                            </div>
                        </td>
                        <td class="unit-price">￥{{s.goods.price}}</td>
               
                        <td class="total_price">{{s.allTotal}}</td>
                        <td>
                            <a href="{% url 'shopcart:delete' s.id %}" class="delete">删除</a>
                        </td>
                    </tr>
                   
                </tbody>
								{% endfor %}
            </table>
			

        </div>
        <div class="clearfix Ri">
            <a href="{% url 'users:user_index' %}" class="continue_shop fl" ><img src="/static/imgs/img/shopping_1.jpg"></a>
						<input type="submit" value="确认订单" class="now_pay fl" width="100" height="100" />	
            
        </div>
		</form>
    </div>
</div>







<!--bottom-->
<div id="bottom-wrap">
    <div id="bottom">
        <div class="user-help fl">
            <h2>用户帮助</h2>
            <ul style="list-style:circle;">
                <li><a href="#">玩转步淘商城</a></li>
                <li><a href="#">生活商城常见问题</a></li>
                <li><a href="#">网站的保障计划</a></li>
                <li><a href="#">本站意见建议</a></li>
            </ul>
        </div>
        <div class="user-help fl">
            <h3>购物相关</h3>
            <ul style="list-style:circle;">
                <li><a href="#">本店商户入驻</a></li>
                <li><a href="#">本店商户登录</a></li>
                <li><a href="#">本站合作案例</a></li>
                <li><a href="#">步淘友情链接</a></li>
            </ul>
        </div>

        <div class="user-help fl">
            <h4>商务合作</h4>
            <ul style="list-style:circle;">
                <li><a href="#">玩转步淘商城</a></li>
                <li><a href="#">生活商城常见问题</a></li>
                <li><a href="#">网站的保障计划</a></li>
                <li><a href="#">本站意见建议</a></li>
            </ul>
        </div>

        <div class="user-help fl">
            <h5>关于步淘</h5>
            <ul style="list-style:circle;">
                <li><a href="#">关于生活商城</a></li>
                <li><a href="#">步淘网聘英才</a></li>
                <li><a href="#">联系步淘网</a></li>
                <li><a href="#">生活商城用户协议</a></li>
            </ul>
        </div>

        <div class="bot-detial fl">
            <h3>客户服务热线<b>(长途免费)</b></h3>
            <span>400-680-2212</span>
            <div>QQ在线客服</div>
            <p>(周一到周日:8:30-18:00)</p>
        </div>
    </div>
</div>
<!--links-->
<div id="links-wrap">
    <div id="links">
        <ul>
            <li><a href="#" class="about">关于步淘    丨</a></li>
            <li><a href="#">联系我们   丨 </a></li>
            <li><a href="#">诚聘精英   丨</a></li>
            <li><a href="#">友情链接   丨 </a></li>
            <li><a href="#">隐私条款   丨</a></li>
            <li><a href="#">网站地图   丨</a> </li>
        </ul>

    </div>
</div>
<!--footer-->
<div id="footer">
    <p>Copyright @ 2010-2012 butao.com Allright Resevred 版权所有 浙B2-20090126-17</p>
    <img src="/static/imgs/img/foot1.png" class="ft-img">
    <img src="/static/imgs/img/foot2.png">
    <img src="/static/imgs/img/foot1.png">
    <img src="/static/imgs/img/footer4).png" class="ft-img4">
</div>
</body>
</html>

dayWeb/myshopping/shopcart/templates/shopcart/list2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查看我的购物车</title>
</head>
<body>
	<div id="content">
		<h1>您的购物车如下：</h1>
		<h3><a href="{% url 'users:user_index' %}">返回主页</a></h3>
		
		<form action="{% url 'orders:confirm' %}" method="post">
		{% csrf_token %}
			<table border="" cellspacing="0" cellpadding="">
				
				<tr>
					<th>商品名称</th>
					<th>商品图片</th>
					<th>商品数量</th>
					<th>商品单价</th>
					<th>商品总价</th>
					<th>操作</th>
				</tr>
				{% for s in shopcarts %}	
					<tr>
						<td><input type="checkbox" name="s_id" value="{{s.id}}" />{{s.goods.name}}</td>
						<td><img src="/{{s.goods.goodsimage_set.all.first.path}}" width="150" height="150" ></td>
						<td>{{s.count}}</td>
						<td>{{s.goods.price}}</td>
						<td>{{s.allTotal}}</td>
						<td>
							<a href="{% url 'shopcart:delete' s.id %}">删除</a>
						</td>
					</tr>
				
					{% empty %}
					<tr>
						<td>购物车没有商品哦，<a href="">去添加吧</a></td>
					</tr>
					
					
				
				{% endfor %}
			</table>
			<br>				
			<input type="submit" value="确认订单" />				
				
		</form>
		
	</div>
</body>
</html>