dayWeb/myshopping/goods/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(\d+)/add/$', views.add, name='add'),
    url(r'^index/$', views.index, name='index'),
    url(r'^findTypePid/$', views.findTypePid, name='findTypePid'),
    #显示所有商品
    url(r'^(\d+)/list/$', views.list, name='list'),
    #删除商品
    url(r'^(\d+)/(\d+)/delete/$', views.delete, name='delete'),
    #修改商品
    url(r'^(\d+)/update/$', views.update, name='update'),
    #购买时候商品详情
    url(r'^(\d+)/detail/$', views.detail, name='detail'),

]

dayWeb/myshopping/myshopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('users.urls', namespace='users')),
    url(r'^store/', include('store.urls', namespace='store')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^shopcart/', include('shopcart.urls', namespace='shopcart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
]

dayWeb/myshopping/orders/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    #确认订单
    url(r'^confirm/$', views.confirm, name='confirm'),
    #支付订单
    url(r'^pay/$', views.pay, name='pay'),
    #生成订单
    url(r'^done/$', views.done, name='done'),
    #查看订单
    url(r'^list/$', views.list, name='list'),
    #订单详情
    url(r'^(\d+)/detail/$', views.detail, name='detail'),
    #删除订单
    url(r'^(\d+)/delete/$', views.delete, name='delete'),

]

dayWeb/myshopping/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_register/$', views.user_register, name='user_register'),
    url(r'^index/', views.index, name='index'),

    url(r'^login_success/$', views.login_success, name='login_success'),
    url(r'^register_success/$', views.register_success, name='register_success'),
    #登录成功的主页
    url(r'^user_index/$', views.user_index, name='user_index'),
    #个人资料
    url(r'^user_info/$', views.user_info, name='user_info'),
    #个人资料修改
    url(r'^user_update/$', views.user_update, name='user_update'),
    #退出
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    # 添加收获地址
    url(r'^add_address/$', views.add_address, name='add_address'),
    #查看所有收获地址
    url(r'^list_address/$', views.list_address, name='list_address'),
    #删除收获地址
    url(r'^(\d+)/delete_address/$', views.delete_address, name='delete_address'),
    #修改收获地址
    url(r'^(\d+)/update_address/$', views.update_address, name='update_address'),
]

dayWeb/myshopping/goods/models.py
from django.db import models

# Create your models here.
# from myshopping.store.models import Store
from store.models import Store


class GoodsType(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, unique=True, verbose_name='商品类型名称')
    cover = models.ImageField(upload_to='static/imgs/goods', default='static/imgs/goods/aaa.png', verbose_name='商品类型插图')
    intro = models.TextField(verbose_name='商品类型描述')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, verbose_name='父级类型')


class Goods(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, verbose_name='商品名称')
    # price = models.DecimalField(max_digits=8, decimal_places=2)
    price = models.FloatField(verbose_name='商品单价')
    stock = models.IntegerField(verbose_name='库存')
    count = models.IntegerField(default=0, verbose_name='销量')
    createTime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    intro = models.TextField()
    store = models.ForeignKey(Store, on_delete=models.CASCADE, verbose_name='商品所属商店')
    goodstype = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name='商品类型')


class GoodsImage(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/imgs/goods', default='static/imgs/goods/aaa.png', verbose_name='商品图片')
    status = models.BooleanField(default=False, verbose_name='是否默认显示该图片')
    intro = models.TextField(null=True, blank=True, verbose_name='商品描述')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='所属商品')

dayWeb/myshopping/orders/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class Order(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='订单所属用户')
    createTime = models.DateTimeField(auto_now_add=True, verbose_name='下单时间')
    recv_name = models.CharField(max_length=100, verbose_name='收件人')
    recv_tel = models.CharField(max_length=100, verbose_name='收件人电话')
    recv_address = models.CharField(max_length=255, verbose_name='收件地址')
    allPrice = models.CharField(max_length=100, verbose_name='订单总金额')
    remark = models.CharField(max_length=255, verbose_name='订单备注')


class OrderItem(models.Model):
    id = models.AutoField(primary_key=True)
    goods_id = models.IntegerField(verbose_name='商品编号')
    goods_img = models.CharField(max_length=255, verbose_name='商品图片')
    goods_name = models.CharField(max_length=100, verbose_name='商品名称')
    goods_price = models.FloatField(verbose_name='商品单价')
    goods_count = models.IntegerField(verbose_name='商品数量')
    goods_allprice = models.FloatField(verbose_name='商品总价')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='订单')

dayWeb/myshopping/orders/views.py
from django.shortcuts import render, redirect, reverse

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from shopcart.models import ShopCart
from goods.models import Goods
from users.models import Address
from . import models


@require_POST
def confirm(req):
    s_ids = req.POST.getlist('s_id')
    shopCarts = ShopCart.objects.filter(pk__in=s_ids)
    addresses = Address.objects.filter(user=req.user)

    return render(req, 'orders/confirm.html', {'shopCarts': shopCarts, 'addresses': addresses})


def pay(req):
    #第三方插件 支付宝 微信 往上银行等
    pass


@require_POST
def done(req):
    s_ids = req.POST.getlist('s_id')
    address_id = req.POST['address']
    remark = req.POST['remark']
    shopCares = ShopCart.objects.filter(pk__in=s_ids)
    address = Address.objects.get(pk=address_id)

    #拼接收获地址
    _address = address.province + '|' +\
                address.city + '|' + address.area + '|' + address.street + '|' + address.desc


    # 生成订单
    order = models.Order(recv_address=_address, user=req.user, recv_name=address.recv_name, recv_tel=address.recv_tel,\
                         allPrice=0, remark=remark)
    order.save()

    allCount = 0

    for s in shopCares:
        g = s.goods
        orderItem = models.OrderItem(goods_id=g.id, goods_img=g.goodsimage_set.all().first().path,\
                         goods_name=g.name, goods_price=g.price, goods_count=s.count,\
                         goods_allprice=s.allTotal, order=order)
        orderItem.save()

        allCount += s.allTotal

    order.allPrice = allCount
    order.save()
    return redirect(reverse('orders:list'))


@login_required
def list(req):
    orders = models.Order.objects.filter(user=req.user)

    return render(req, 'orders/list.html', {'orders': orders,})


def delete(req, oid):
    order = models.Order.objects.get(pk=oid)
    order.delete()
    return redirect(reverse('orders:list'))


def detail(req, o_id):
    pass

dayWeb/myshopping/orders/templates/orders/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>确认订单</title>
	<style type="text/css">
		body{
			background-image: url("/static/imgs/orders/999.jpg");
			background-size: 1200px;
		}
		#addGoods, #a2{
			margin-left: 30px;
		}
	</style>
</head>
<body>
	<div id="content">
		<h1>请确认订单：</h1>
		<h3>
			<a href="{% url 'users:user_index' %}">返回主页</a>
			<a id="a2" href="{% url 'shopcart:list' %}">返回购物车</a>
		</h3>
		<form action="{% url 'orders:done' %}" method="post">
		{% csrf_token %}
			
			<table border="" cellspacing="0" cellpadding="">
				
				<tr>
					<th>商品名称</th>
					<th>商品图片</th>
					<th>商品数量</th>
					<th>商品单价</th>
					<th>商品总价</th>
					<th>订单备注</th>
				</tr>
				{% for s in shopCarts %}	
				
					<input type="hidden" name="s_id" value="{{s.id}}" />
					<tr>
						<td>{{s.goods.name}}</td>
						<td><img src="/{{s.goods.goodsimage_set.all.first.path}}" width="100" height="100" ></td>
						<td>{{s.count}}</td>
						<td>{{s.goods.price}}</td>
						<td>{{s.allTotal}}</td>
						<td>
							<textarea rows="5" cols="20" name="remark">
								
							</textarea>
						</td>
					</tr>
		
				{% endfor %}
			</table>
			<br>
			<h3>请选择收获地址：</h3>
			<table border="" cellspacing="0" cellpadding="">
				
				<tr>
					<th>收货人</th>
					<th>电话号码</th>
					<th>收获地址</th>
					<th>默认</th>
				</tr>
				{% for address in addresses %}
					<tr>
						<td>{{address.recv_name}}</td>
						<td>{{address.recv_tel}}</td>
						<td>{{address.province}} {{address.city}} {{address.area}} {{address.street}} {{address.desc}}</td>
						{% if address.is_default %}
							<td><input type="radio" name="address" value="{{address.id}}" checked /></td>
						{% else %}
							<td><input type="radio" name="address" value="{{address.id}}" checked /></td>
						{% endif %}
					</tr>
	
				{% endfor %}
			</table>
			<br>
	
			<input type="submit" value="生成订单" />	
		</form>
		
	</div>
</body>
</html>

dayWeb/myshopping/orders/templates/orders/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

dayWeb/myshopping/orders/templates/orders/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购物车</title>
    <link rel="stylesheet" type="text/css" href="/static/css/shop-car.css">
    <link rel="stylesheet" type="text/css" href="/static/css/common.css">
    <link rel="stylesheet" type="text/css" href="/static/css/index.css">
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script src="/static/js/the_Same.js"></script>
    <script src="/static/js/shop-car.js"></script>
	<style type="text/css">
		.aa1{
			margin-right: 10px;
		}
	</style>
</head>
<body>



<!--导航-->
<div id="nav-wrap">
    <div id="nav">
        <ul>
            <li><a href="{% url 'users:user_index' %}" class="nav-page">首页</a></li>
            <li><a href="{% url 'store:add' %}">添加店铺</a></li>
            <li><a href="">店铺主页</a></li>
            <li><a href="#">品牌男装</a></li>
            <li><a href="#" >积分抽奖</a></li>
            <li><a href="#" >特价商品</a><span></span></li>
            <li><a href="#" class="nav-balabala">巴拉巴拉专区</a></li>
            <li><a href="#">签到换礼</a></li>
        </ul>

    </div>
</div>
<!--购物车内容-->
<div class="shopping_car_wrap">
    <div class="shopping_car">
        <!-- <div class="shop_menu"><img src="/static/imgs/img/shopping_car.jpg"></div> -->
		<h1>您的所有订单：</h1>
		<br>
		<br>

        <div class="updater-list">
            <table class="shop_table">
                <thead>
                    <tr>
                        <th colspan="1">收货人</th>
						<th colspan="1">收货电话</th>
       
                        <th width="100">收货地址</th>
						<th width="100">商品名称</th>
						<th width="100">商品总价</th>
						<th width="100">商品数量</th>
						<th width="100">订单备注</th>
						<th width="100">订单操作</th>
                    
                    </tr>
                </thead>
				{% for o in orders %}
                <tbody>
                    <tr class="shop_car_con">
                        
                        <td width="100">
                            <p>{{o.recv_name}}</p>
                            
                        </td>
						<td width="100">{{o.recv_tel}}</td>
						<td class="unit-price" width="200">{{o.recv_address}}</td>
						<td>{{o.orderitem_set.all.first.goods_name}}</td>
						<td>{{o.allPrice}}</td>
						<td>{{o.orderitem_set.all.first.goods_count}}</td>
						<td>{{o.remark}}</td>
						<td>
							<a class="aa1" href="{% url 'orders:delete' o.id %}">删除</a>
							<a class="aa1" href="">结算</a>
						</td>
					</tr>
			
				{% empty %}
				<tr>
					<td>购物车没有商品哦，<a href="">去添加吧</a></td>
				</tr>
                   
                </tbody>
				{% endfor %}
            </table>

        </div>

</div>







<!--bottom-->
<div id="bottom-wrap">
    <div id="bottom">
        <div class="user-help fl">
            <h2>用户帮助</h2>
            <ul style="list-style:circle;">
                <li><a href="#">玩转步淘商城</a></li>
                <li><a href="#">生活商城常见问题</a></li>
                <li><a href="#">网站的保障计划</a></li>
                <li><a href="#">本站意见建议</a></li>
            </ul>
        </div>
        <div class="user-help fl">
            <h3>购物相关</h3>
            <ul style="list-style:circle;">
                <li><a href="#">本店商户入驻</a></li>
                <li><a href="#">本店商户登录</a></li>
                <li><a href="#">本站合作案例</a></li>
                <li><a href="#">步淘友情链接</a></li>
            </ul>
        </div>

        <div class="user-help fl">
            <h4>商务合作</h4>
            <ul style="list-style:circle;">
                <li><a href="#">玩转步淘商城</a></li>
                <li><a href="#">生活商城常见问题</a></li>
                <li><a href="#">网站的保障计划</a></li>
                <li><a href="#">本站意见建议</a></li>
            </ul>
        </div>

        <div class="user-help fl">
            <h5>关于步淘</h5>
            <ul style="list-style:circle;">
                <li><a href="#">关于生活商城</a></li>
                <li><a href="#">步淘网聘英才</a></li>
                <li><a href="#">联系步淘网</a></li>
                <li><a href="#">生活商城用户协议</a></li>
            </ul>
        </div>

        <div class="bot-detial fl">
            <h3>客户服务热线<b>(长途免费)</b></h3>
            <span>400-680-2212</span>
            <div>QQ在线客服</div>
            <p>(周一到周日:8:30-18:00)</p>
        </div>
    </div>
</div>
<!--links-->
<div id="links-wrap">
    <div id="links">
        <ul>
            <li><a href="#" class="about">关于步淘    丨</a></li>
            <li><a href="#">联系我们   丨 </a></li>
            <li><a href="#">诚聘精英   丨</a></li>
            <li><a href="#">友情链接   丨 </a></li>
            <li><a href="#">隐私条款   丨</a></li>
            <li><a href="#">网站地图   丨</a> </li>
        </ul>

    </div>
</div>
<!--footer-->
<div id="footer">
    <p>Copyright @ 2010-2012 butao.com Allright Resevred 版权所有 浙B2-20090126-17</p>
    <img src="/static/imgs/img/foot1.png" class="ft-img">
    <img src="/static/imgs/img/foot2.png">
    <img src="/static/imgs/img/foot1.png">
    <img src="/static/imgs/img/footer4).png" class="ft-img4">
</div>
</body>
</html>

dayWeb/myshopping/orders/templates/orders/list2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询所有订单</title>
	<style type="text/css">
		body{
			background-image: url("/static/imgs/orders/999.jpg");
			background-size: 1200px;
		}
	</style>
</head>
<body>
	<div id="content">
		<h1>您的所有订单：</h1>
		
		<table border="" cellspacing="0" cellpadding="">
			<tr>
				<th>收货人</th>
				<th>收货电话</th>
				<th>收货地址</th>
				<th>商品名称</th>
				<th>商品总价</th>
				<th>商品数量</th>
				<th>订单备注</th>
				<th>订单操作</th>
			</tr>
			{% for o in orders %}
				<tr>
					<td>{{o.recv_name}}</td>
					<td>{{o.recv_tel}}</td>
					<td>{{o.recv_address}}</td>
					<td>{{o.orderitem_set.all.first.goods_name}}</td>
					<td>{{o.allPrice}}</td>
					<td>{{o.orderitem_set.all.first.goods_count}}</td>
					<td>{{o.remark}}</td>
					<td>
						<a href="{% url 'orders:delete' o.id %}">删除</a>;
						<a href="">结算</a>
					</td>
				</tr>
			
				{% empty %}
				<tr>
					<td>购物车没有商品哦，<a href="">去添加吧</a></td>
				</tr>
				
				
			
			{% endfor %}
		</table>
		<br>
		<h3>
			<a href="{% url 'users:user_index' %}">返回主页</a>
		</h3>
		
		
		
	</div>
</body>
</html>

dayWeb/myshopping/orders/templates/orders/pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>