Dian/pinduo/goods/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # 测试添加商品
    url(r"^add/$", views.add, name="add"),
    # 对应商品ID传到页面的功能
    url(r"^(?P<g_id>\d+)/detail/$", views.detail, name="detail"),
    # 获取商品
    url(r"^findTypeBuId/$", views.findTypeBuId, name="findTypeBuId"),
    url(r"^(?P<s_id>\d+)/(?P<g_id>\d+)/delete_goods/$", views.delete_goods, name="delete_goods"),

]

Dian/pinduo/orders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^confirm/$', views.confirm, name="confirm"),
    url(r'^pay/$', views.pay, name="pay"),
    url(r'^done/$', views.done, name="done"),
    url(r'^list/$', views.list, name="list"),
    url(r'^(?P<o_id>\d+)/delete_order/$', views.delete_order, name="delete_order"),
    url(r'^(?P<o_id>\d+)/detail/$', views.detail, name="detail"),
]

Dian/pinduo/pinduo/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/',include("haystack.urls")),
    url(r'^users/', include("users.urls", namespace='users')),
    url(r'^goods/', include("goods.urls", namespace='goods')),
    url(r'^store/', include("store.urls",namespace='store')),
    url(r'^orders/', include("orders.urls",namespace='orders')),
    url(r'^shopcart/', include("shopcart.urls",namespace='shopcart')),
    url(r'^', include("commons.urls",namespace='commons')),



    url(r'^utils/', include("utils.urls", namespace='utils')),

]

Dian/pinduo/shopcart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^listt/$", views.listt, name="listt"),         #购物车
    url(r"^add/$", views.add, name="add"),            #添加商品
    # url(r"^shopcar/$", views.shopcar, name="shopcar"),
    url(r"^zj/$", views.zj, name="zj"),       #购物车商品变更
]

Dian/pinduo/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # 用户登录
    url(r'^user_login/$', views.user_login, name='user_login'),
    # 退出用户登录状态
    url(r'del_login/$', views.del_login, name='del_login'),
    # 注册用户
    url(r'^user_register/$', views.user_register, name='user_register'),
    # 未了解
    url(r'^code/$', views.code, name='code'),
    # 用户首页
    url(r'^index/$', views.index, name='index'),
    # 修改用户
    url(r'^update/$', views.update, name='update'),
    # 传入用户名参数，检查用户名是否存在
    url(r'^(?P<username>\w+)/check_username/$',views.check_username, name='check_username'),
    # 修改用户头像
    url(r'^update_head/$', views.update_head, name='update_head'),
    # 修改用户密码
    url(r'^(?P<u_id>\d+)/update_password/$', views.update_password, name='update_password'),
    # 用户地址列表
    url(r'address_list/$', views.address_list, name='address_list'),
    # 删除用户地址
    url(r'(?P<id>\d+)/delete_address/$', views.delete_address, name='delete_address'),
    # 添加用户地址
    url(r'aaa/$', views.aaa,name='aaa'),
    # 邮箱注册
    url(r'login1/$', views.login1, name='login1'),
    url(r'active/$', views.active, name='active'),

]

Dian/pinduo/goods/models.py
from django.db import models
# 导入店铺
# import store
from store.models import Store


#商品类型表
class GoodsType(models.Model):
    #商品id
    id = models.AutoField(primary_key=True)
    #商品类型名称
    name = models.CharField(max_length=255,unique=True,verbose_name="商品类型名称")
    #商品图片
    cover = models.ImageField(upload_to="static/images/goods",default="static/images/goods/default.jpg",verbose_name="商品图片")
    #商品类别描述
    intro = models.TextField(verbose_name="商品类别描述")
    #父级类型(自关联)
    parent = models.ForeignKey('self',null=True,blank=True,verbose_name="父级类型",on_delete=models.CASCADE)

    def __str__(self):
        return self.name


#商品列表
class Goods(models.Model):
    id = models.AutoField(primary_key=True)
    #商品名称
    name = models.CharField(max_length=255,verbose_name="商品名称")
    #商品单价(更准确的表示浮点数的数据Decimal  max_digits有效位数)
    # price = models.DecimalField(max_digits=8,decimal_places=2)
    price = models.FloatField(verbose_name="商品单价")
    #库存
    stock = models.IntegerField()
    #销量
    count = models.IntegerField(default=0)
    #上架时间
    creatTime = models.DateTimeField(auto_now_add=True)
    # 商品介绍
    intro = models.TextField()
    # 构造内键
    store = models.ForeignKey(Store, on_delete=models.CASCADE,verbose_name="商品所属商店")
    #构造外键
    goodstype = models.ForeignKey(GoodsType,on_delete=models.CASCADE,verbose_name="商品类型")

    def __str__(self):
        return self.name


#图片类
class GoodsImages(models.Model):
    id = models.AutoField(primary_key=True)
    #商品图片
    path = models.ImageField(upload_to="static/images/goods",default="static/images/goods/default.jpg",verbose_name="商品图片")
    #商品状态
    status = models.BooleanField(default=False,verbose_name="是否显示该图片")
    #商品图片描述
    intro = models.TextField(verbose_name="商品图片描述",null=True,blank=True)
    #所属商品
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name="所属商品")

Dian/pinduo/orders/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
#一个订单表
class Orders(models.Model):
    id = models.AutoField(primary_key=True)
    # 订单所属用户
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="订单所属用户")
    # 订单生成时间
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="订单生成时间")
    # 收件人
    recv_name = models.CharField(max_length=100, verbose_name="收件人")
    # 收件人电话
    recv_tel = models.CharField(max_length=50, verbose_name="收件人电话")
    # 收件地址
    recv_address = models.CharField(max_length=255, verbose_name="收件地址")
    # 订单总金额
    all_price = models.FloatField(verbose_name="订单总金额")
    # 订单备注
    remark = models.CharField(max_length=255, verbose_name="订单备注")


#这是一个订单商品表
class orders_item(models.Model):
    id = models.AutoField(primary_key=True)
    # 商品的编号
    goods_id = models.IntegerField(verbose_name="商品编号")
    # 商品图片
    goods_img = models.CharField(max_length=255, verbose_name="商品图片")
    # 商品名称
    goods_name = models.CharField(max_length=100, verbose_name="商品名称")
    # 商品价格
    goods_price = models.FloatField(verbose_name="商品价格")
    # 商品数量
    goods_count = models.IntegerField(verbose_name="商品数量")
    # 商品总价
    goods_price_all = models.FloatField(verbose_name="商品总价")
    # 所属的订单
    order = models.ForeignKey(Orders, on_delete=models.CASCADE, verbose_name="订单")
    def __str__(self):
        return self.goods_name

Dian/pinduo/orders/views.py
from django.shortcuts import render,redirect,reverse
from django.views.decorators.http import require_POST

from shopcart.models import ShopCart
from goods.models import Goods
from users.models import Address
from . import models


# @require_POST
def confirm(request):
    """
    把对应商品添加到订单上，确认订单信息
    :param request:
    :return:
    """
    # 收货地址
    # count = request.POST.getlist("count")
    # 获取购物车中数据的id，把对应商品添加到订单中
    g_ids = request.POST.getlist("s_id")
    shopCarts = ShopCart.objects.filter(pk__in=g_ids)
    address = Address.objects.filter(user=request.user)
    shopcarts1 = ShopCart.objects.filter(user=request.user)
    print(shopcarts1)
    # 计算总价
    i = 0
    for zj in shopcarts1:
        i += zj.allTotal
        print(i)

    return render(request,'orders/confirm.html',{"shopCarts":shopCarts,"address":address,"i":i})


def pay(request):       # 支付，待完善
    pass


def done(request):
    """
    将订单中的商品存储到数据库中，然后根据订单中的商品计算总额
    :param request:
    :return:
    """

    # 从界面获取购物车商品ID
    c_ids = request.POST.getlist("c_id")
    # 从界面获取选择的地址ID
    address_id = request.POST["address"]
    # 获取地址对象
    address = Address.objects.get(pk=address_id)
    # 编辑存入订单里的地址
    _address = address.province + " " + address.city + " " + address.area + "  " + address.desc
    # 生成订单
    order = models.Orders(recv_address=_address,user=request.user,recv_name=address.recv_name,recv_tel=address.recv_tel,all_price=0,remark='')
    order.save()

    allCount = 0
    # 获取购物车里的商品对象
    shopcars = ShopCart.objects.filter(pk__in=c_ids)
    # 遍历购物车里的商品，将订单提交到数据库
    for s in shopcars:
        g = s.goods
        orderItem = models.orders_item(goods_id=g.id,goods_img=g.goodsimages_set.all().first().path,goods_name=g.name,goods_price=g.price,goods_count=s.count,goods_price_all=s.allTotal,order=order)
        orderItem.save()
        allCount += s.allTotal
    # 小计
    order.all_price = allCount
    order.save()

    return redirect(reverse("orders:list"))


# 查看订单
def list(request):
    """
    查询所有的订单信息
    :param request:
    :return:
    """
    # 查询订单所属的用户
    orders = models.Orders.objects.filter(user=request.user)
    # 查询商品属于那个订单
    orderitem = models.orders_item.objects.filter(order=orders)

    return render(request,"orders/list1.html",{"orders":orders,"orderItem":orderitem})


# 商品详情
def detail(request, o_id):
    """
    查看单个订单的所有商品
    :param request:
    :param o_id:
    :return:
    """
    orderItem = models.orders_item.objects.filter(order_id=o_id)

    return render(request,"orders/detail.html",{"orderItem": orderItem})


def delete_order(request, o_id):
    """
    删除订单，从数据库中删除
    :param request:
    :param o_id:
    :return:
    """
    order = models.Orders.objects.get(pk=o_id)
    order.delete()

    return redirect(reverse("orders:list"))

Dian/pinduo/orders/templates/orders/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>购物车</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/index.css' %}">
	<link rel="stylesheet" href="{% static 'css/shopcar2.css' %}">
	<link rel="stylesheet" href="{% static 'css/product.css' %}">
	<script type="text/javascript" src="{% static 'js/lib/jquery/jquery-1.12.4.min.js' %}"></script>

	<!--<script type="text/javascript" src="../js/index.js"></script>-->
	<script type="text/javascript" src="{% static 'js/lib/jquery/index.js' %}"></script>
	<!--<script type="text/javascript" src="../js/jquery.validate.js"></script>-->
	<script type="text/javascript" src="{% static 'js/lib/jquery/jquery.validate.js' %}"></script>
	<!--<script type="text/javascript" src="../js/messages_zh.js"></script>-->
	<script type="text/javascript" src="{% static 'js/lib/jquery/messages_zh.js' %}"></script>
	<!--<script type="text/javascript" src="../js/jquery.cookie.js" ></script>-->
	<script type="text/javascript" src="{% static 'js/lib/jquery/jquery.cookie.js' %}" ></script>
	<!--<script type="text/javascript" src="../js/shopcart.js" ></script>-->
	<script type="text/javascript" src="{% static 'js/lib/jquery/shopcart.js' %}" ></script>
	<script type="text/javascript" src="{% static 'js/lib/jquery/product.js' %}" ></script>
	<!--<script type="text/javascript" src="../js/shopcar.js"></script>-->
	<script type="text/javascript" src="{% static 'js/lib/jquery/shopcar.js' %}"></script>


</head>
<body>
	<!-- global-nav -->
	<div id="global-nav">
		<div class="global-nav">
			<ul class="global-fl">
				<li class="nav-toindex"><a href="{% url 'users:index' %}">返回首页</a></li>
				<li class="nav-collect"><a href="#">收藏网站</a></li>
			</ul>
			<div class="global-fr">
				<ul class="global-login">
					<li>您好，欢迎光临韩都衣舍！</li>

					{% if request.session.loginUser %}
						<li><a href="#">{{request.session.loginUser}}</a></li>
						<li><a href="/users/del_login"><span>退出</span></a></li>
					{% else %}
						<li><a href="/users/user_login/">登录</a></li>
						<li><a href="{% url 'users:user_register' %}"><span>注册</span></a></li>
					{% endif %}
					<li><a href="{% url 'shopcart:listt' %}">购物车</a></li>
				</ul>
				<ul class="global-help">
					<li><a href="#">在线客服</a></li>
					<li><a href="#">帮助中心</a></li>
					<li id="site-nav-display"><a  href="#"><span></span>网站导航</a>
						<ul class="site-nav">
							<li class="nav-hot">
								<h2>大家都在买 Hot</h2>
								<a href="">T恤</a>
								<a href="">连衣裙</a>
								<a href="">牛仔裤</a>
								<a href="">毛衣针织</a>
								<a href="">卫衣绒衫</a>
								<a href="">休闲套装</a>
							</li>
							<li class="nav-women">
								<h2>女装  Women</h2>
								<a href="">韩风快时尚女装</a>
								<a href="">韩风快时尚妈妈装</a>
								<a href="">韩风甜美少女装</a>
								<a href="">韩风复古设计师女装</a>
								<a href="">韩风名媛时尚女装</a>
								<a href="">欧美浪漫田园风女装</a>
								<a href="">韩风大码女装</a>
								<a href="">欧美快时尚女装</a>
							</li>
							<li class="nav-men one-line">
								<h2>男装 Men</h2>
								<a href="">韩风快时尚男装</a>
								<a href="">东方禅意设计师男装</a>
								<a href="">欧美街头轻潮男装</a>
							</li>
							<li class="nav-children one-line">
								<h2>童装 Children</h2>
								<a href="">韩风快时尚童装</a>
								<a href="">东方简约设计师童装</a>
							</li>
							<li class="nav-help" style="border:0">
								<h2>帮助中心 Help</h2>
								<a href="">会员制度</a>
								<a href="">售后服务</a>
								<a href="">购物流程</a>
								<a href="">韩都招聘</a>
							</li>
						</ul>
					</li>
				</ul>
			</div>

		</div>

	</div>


	<!-- 购物车内容 -->
	<div class='cart_header'>
	    <a href="" class='cart_logo fl'></a>
	    <div class='cart_step step2 fr'></div>
	</div>
	<div class='wrap'>

		{% if address %}
		<form id="formCart" name="formCart" method="post" action="{% url 'orders:done' %}">
			{% else %}
				<form action="{% url 'users:aaa' %}">
					{% endif %}
		<div class='warm_tip'><span>温馨提示：</span>购物车中商品无法保留库存，请您及时下单结算</div>
	    <div class="shopping_nr">
		    				{% csrf_token %}
		        <div class="shopping_nr_title">
		            <div class="shop_qx" style="width: 40px;"> </div>
		            <div class="shop_qx" style="width: 450px;">宝贝</div>
		            <div class="shop_qx" style="width: 117px;">名称</div>
		            <div class="shop_qx" style="width: 143px;">数量</div>
		            <div class="shop_qx" style="width: 157px;">小计</div>
		            <div class="shop_qx" style="width: 162px;">操作</div>
		        </div>
                {% for s in  shopCarts %}
				<input type="hidden" name="c_id" checked value="{{s.id}}">
				<div class="shopping_nr_title1">
		            <div class="shop_qx" style="width: 40px;"></div>
		            <div class="shop_qx" style="width: 452px;"><img src="/{{s.goods.goodsimages_set.all.first.path}}" style="height: 60px;width:60px;border-radius:50%;margin-left:200px;"></div>
		            <div class="shop_qx" style="width: 117px;"><span class="price">{{s.goods.name}}</span></div>
		            <div class="shop_qx" style="width: 143px;">
						 {{s.count}}
					</div>
		            <div class="shop_qx" style="width: 157px;" ><span class="subtotal">{{s.allTotal}}</span></div>
		            <div class="shop_qx" style="width: 162px;">无</div>
		        </div>

                {% endfor %}
				<div class="shopcart scBox">
					<table>

						<tbody class="cartItems">
						</tbody>
					</table>
				</div>


		        <div class="shopping_car_bottom">
		        </div>
		        <div class="shopping_car_bottom shopping_car_bottom_bg">
		            <div class="shopping_car_bottom_right">
		                <span class="shopping_car_bottom_rightMoney">
		                    <span style="line-height:50px;">
		                        购物金额总计：

		                        <span style="min-width:75px;display:inline-block;text-align:right;">
		                        	<span style="color:#bf0000; font-size:18px;">￥
										{{i}}
									</span>
		                          	<span id=""></span>
		                        </span>
		                    </span>
		                </span>

		            </div>
		        </div>
				<div class="shopping_nr_title">
		            <div class="shop_qx" style="width: 40px;"> </div>
		            <div class="shop_qx" style="width: 600px;"><a href="{% url 'users:aaa' %}">添加收货地址</a></div>
		            <div class="shop_qx" style="width: 1px;"></div>
		            <div class="shop_qx" style="width: 1px;"></div>
		            <div class="shop_qx" style="width: 1px;"></div>
		            <div class="shop_qx" style="width: 1px;"></div>
		        </div>
                {% for a in address %}
				<div class="shopping_nr_title2">
		            <div class="shop_qx" style="width: 60px;"><input type="radio" name="address" id="address" value="{{a.id}}"></div>
		            <div class="shop_qx" style="width: 600px;">
						<p>
							{{a.recv_name}}
							{{a.recv_tel}}
							{{a.province}}
							{{a.city}}
							{{a.area}}
							{{a.street}}
							{{a.id}}
						</p>
					</div>
		            <div class="shop_qx" style="width: 1px;"></div>
		            <div class="shop_qx" style="width: 1px;">

					</div>
		            <div class="shop_qx" style="width: 1px;"></div>
		            <div class="shop_qx" style="width: 1px;"></div>
		        </div>
                {% endfor %}
			</div>
			<button type="submit" style="margin-left:100px;">跳转</button>
        </form>
		<div class="div_deleted">
		  	<h1 id="show_del_msg"></h1>
			<ul class='deleted'></ul>
		</div>
	</div>

	<!-- footer -->
	<div id="footer">
		<!-- footer-info -->
		<div id="footer-info">
			<div class="footer-info-item">
				<h3 style="background: url(../img/footer01.png) no-repeat -9px 0"></h3>
				<a href="#">用户注册</a>
				<a href="#">购物流程</a>
				<a href="#">网站导航</a>
				<a href="#">帮助中心</a>
			</div>
			<div class="footer-info-item">
				<h3 style="background: url(../img/footer01.png) no-repeat -11px -34px"></h3>
				<a href="#">在线支付</a>
				<a href="#">货到付款</a>
				<a href="#">扫码支付</a>
				<a href="#">优惠券支付</a>
			</div>
			<div class="footer-info-item">
				<h3 style="background: url(../img/footer01.png) no-repeat 0 -67px"></h3>
				<a href="#">配送说明</a>
				<a href="#">运费说明</a>
				<a href="#">验货签收</a>
				<a href="#">货到付款</a>
			</div>
			<div class="footer-info-item">
				<h3 style="background: url(../img/footer01.png) no-repeat -29px -100px"></h3>
				<a href="#">退换货政策</a>
				<a href="#">退换货流程</a>
			</div>
			<div class="footer-info-item">
				<h3 style="background: url(../img/footer01.png) no-repeat -7px -134px"></h3>
				<a href="#">会员支付</a>
				<a href="#">会员积分</a>
				<a href="#">好评有礼</a>
			</div>
			<div class="footer-info-item">
				<h3 style="background: url(../img/footer01.png) no-repeat -9px -202px"></h3>
				<a href="#">品牌故事</a>
				<a href="#">媒体报道</a>
				<a href="#">诚聘英才</a>
				<a href="#">联系我们</a>
			</div>
		</div>
		<!-- footer-feature -->
		<div id="footer-feature">

		</div>
		<!-- footer-nav -->
		<div id="footer-nav">
			<a href="#" target="_blank">首页</a>&nbsp;&nbsp;|&nbsp;&nbsp;
			<a href="#" target="_blank">品牌故事</a>&nbsp;&nbsp;|&nbsp;&nbsp;
			<a href="#" target="_blank">诚聘英才</a>&nbsp;&nbsp;|&nbsp;&nbsp;
			<a href="#" target="_blank">媒体报道</a>&nbsp;&nbsp;|&nbsp;&nbsp;
			<a href="#" target="_blank">联系我们</a>&nbsp;&nbsp;|&nbsp;&nbsp;
			<a href="#" target="_blank">网站地图</a>&nbsp;&nbsp;|&nbsp;&nbsp;
			<a href="#" target="_blank">友情链接</a>
		</div>
		<!--copyright-info-->
		<div id="copyright-info">
			<p>
				<span><img src="../img/copyright.gif" alt=""><b>鲁ICP备14003322号-2 © 2006-2015 handu.com All Rights Reserved.</b></span>
				<span><img src="../img/beiantubiao.png" alt=""><a>鲁公网安备 37010202000113号</a></span>
				<span><b>山东韩都衣舍电商集团有限公司，禁止非法复制</b><img style="margin-top:10px" src="../img/pic.gif" alt=""></span>
			</p>
			<p>
				<img style="height:38px;margin-right:10px;" src="../img/zxmbutton02_sy.jpg" alt="">
				<a href="#"><img style="height:38px;margin-right:10px;" src="../img/zxmbutton05_sy.jpg" alt=""></a>
				<a href="#"><img style="height:38px;margin-right:10px;" src="../img/cnnic.png" alt=""></a>
				<img style="height:38px" src="../img/cctv.png" alt="">
			</p>
		</div>

	</div>

</body>
</html>

Dian/pinduo/orders/templates/orders/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询所有订单</title>
</head>
<body>
    {% for o in orders %}
    {{o.user}}
    {{o.create_time}}
    {{o.recv_name}}
    {{o.recv_address}}
    {{o.all_price}}
    {{o.remark}}<br>
    {% endfor %}
    <br><br>


</body>
</html>